export const favoriteOptions = [
  { value: '180cm', label: '180cm', color: '#F3C4FB' },
  { value: '비흡연자', label: '비흡연자', color: '#E7A4E4' },
  { value: '흡연자', label: '흡연자', color: '#D3A4E5' },
  { value: '키작남', label: '키작남', color: '#A79BFE' },
  { value: '키작녀', label: '키작녀', color: '#B28DFF' },
  { value: '잘생김', label: '잘생김', color: '#92A9BD' },
  { value: '귀여움', label: '귀여움', color: '#9FD3C7' },
  { value: '베이글녀', label: '베이글녀', color: '#B5EAD7 ' },
  { value: '고양이상', label: '고양이상', color: '#C7CEEA ' },
  { value: '강아지상', label: '강아지상', color: '#E2F0CB ' },
  { value: '다정함', label: '다정함', color: '#FBE4C2 ' },
  { value: '외향형', label: '외향형', color: '#F6CDAA ' },
  { value: '내향형', label: '내향형', color: '#F9D5A7 ' },
  { value: '애주가', label: '애주가', color: '#FFDFD3' },
  { value: '술찌', label: '술찌', color: '#ECD5E3 ' },
  { value: '헬창', label: '헬창', color: '#FFC8DD ' },
  { value: '집순집돌이', label: '집순집돌이', color: '#FFB7B2 ' },
  { value: '지적인', label: '지적인', color: '#D5E4FE ' },
  { value: '문과', label: '문과', color: '#A2D2FF' },
  { value: '이과', label: '이과', color: '#BDE0FE' },
  { value: '예체능', label: '예체능', color: '#A2E3C4' }
];
